# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, vars, host, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "thunderbolt" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ae0d4322-4910-4eec-be93-01388c445a9c";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4318-978D";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.

  # networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp86s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;

  networking = with host; {
    networkmanager.enable = true;
    # useDHCP = lib.mkDefault true;
    hostName = hostName;
    firewall = {
      enable = false;
      allowedTCPPorts = [ 80 443 6969 1337 57766 ];
      allowedUDPPorts = [ 80 443 6969 1337 57766 ];
    };

    # bridges = {
    #   "br0" = {
    #     interfaces = [ "enp1s0" ];
    #   };
    # };
    # interfaces = {
    #   # enp1s0 = {
    #   #   useDHCP = false;
    #   #   ipv4.addresses = [{
    #   #     address = "192.168.0.50";
    #   #     prefixLength = 24;
    #   #   }];
    #   # };
    #   # enp2s0.useDHCP = true;
    #   # wlo1.useDHCP = true;
    #   br0 = {
    #     useDHCP = false;
    #     ipv4.addresses = [{
    #       address = "192.168.0.50";
    #       prefixLength = 24;
    #     }];
    #   };
    # };
    # enableIPv6 = false;
    # defaultGateway = "192.168.0.1";
    # nameservers = [ "192.168.0.4" "1.1.1.1" ];
  };

}
